using System.Runtime.Serialization;

namespace CostsSettler.Auth.Exceptions;
[Serializable]
public class NullAccessTokenException : Exception
{
    public NullAccessTokenException()
        : base("The access token could not be generated by Keycloak server") { }

    protected NullAccessTokenException(SerializationInfo info, StreamingContext context)
        : base(info, context) { }
}
