version: '3.3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=TestPassword123
    ports:
      - "1433:1433"

  costs-settler-api:
    build:
      context: .
      dockerfile: ./CostsSettler.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mssql