# docker compose up -d

version: '3.3'

services:
  costs-settler-api:
    env_file:
      - costs-settler-api.env
    image: costssettler.api:latest
    depends_on:
      - mssql
    ports:
      - 8081:443
      - 8082:80

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    env_file:
      - mssql.env
    ports:
      - "1433:1433"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    command: -v start-dev --import-realm
    volumes:
      - ..\keycloak\import:/opt/keycloak/data/import
      - ..\keycloak\tmp:/opt/keycloak/data/h2
    env_file: 
      - keycloak.env
    ports:
      - 8080:8080

  spa:
    image: costssettler.spa:latest
    ports:
      - 80:80
