# docker compose -f docker-compose.build.yaml up -d --build

version: '3.3'

services:
  costs-settler-api:
    build:
      context: .
      dockerfile: ./CostsSettler.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mssql,1433; Database=CostsSettler_DB; User Id=sa; Password=Password!23; TrustServerCertificate=True
      - KeycloakClientConfig__Realm=CostsSettler
      - KeycloakClientConfig__AuthServerUrl=http://keycloak:8080/
      - KeycloakClientConfig__Secret=WPmKFcPu4sN2DE0E9P9fyktx66iv5BG7
      - KeycloakClientConfig__ClientId=CostsSettler-API
    depends_on:
      - mssql
    ports:
      - 8081:443
      - 8082:80

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password!23
    volumes:
      - ..\tmp\mssql:/var/opt/mssql/data
    ports:
      - "1433:1433"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    command: -v start-dev --import-realm
    volumes:
      - ..\keycloak\import:/opt/keycloak/data/import
      - ..\tmp\keycloak:/opt/keycloak/data/h2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
