# docker-compose up -d --build

version: '3.3'

services:
  costs-settler-api:
    build:
      context: .
      dockerfile: ./CostsSettler.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - mssql
    ports:
      - 8081:443
      - 8082:80

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password!23
    ports:
      - "1433:1433"

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    command: start-dev
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080
